### ISSUE TITLE
MRE as a docker hub image.

### ISSUE THREAD

**Issue by upuldi** [microrealestate/microrealestate#108]
If MRE is released as Docker Hub images (similar to Paperless-nginx, Plex, etc.) and we use the Docker Compose script to run it without the mre binaries(./mre-mac), we can use Watchtower docker image to automatically get the latest MRE images from docker-hub which will include feature updates and bug fixes.

**Comment by camelaissani** [comment]
Definitely a good idea and it might help to version the application.
However, before implementing this, the following points have to be resolved:

- Need to find a way to merge the `prod.env` and `.env` file in order to inject the resolved environment variables when running `docker-compose`
The defined variables in the `.env` file replace part of the ones defined in the `prod.env` file. The `prod.env` variables are generic while `.env` are specific as they are created following the execution of the `mre` command.
[code which merges the env](https://github.com/microrealestate/microrealestate/blob/master/cli/src/utils.js#L27-L37)
[code which injects the env to the docker-compose process](https://github.com/microrealestate/microrealestate/blob/master/cli/src/utils.js#L117)
 
- Adapt the NextJS frontends to be able to inject runtime environment variables that can be read from the browser
Without solving this problem, it is impossible to have reusable images for the frontends. The images created contain the specific environment variables coming from `.env`file. See the args [here](https://github.com/microrealestate/microrealestate/blob/master/docker-compose.microservices.base.yml#L166-L183) and [here](https://github.com/microrealestate/microrealestate/blob/master/docker-compose.microservices.base.yml#L198-L214).
Extract of the NextJS doc:  
> This inlining occurs at build time, so your various NEXT_PUBLIC_ envs need to be set when the project is built.
[more here](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser)
 
- Setup a CI/CD pipeline in order to push the created images in docker hub or similar repository (work in progress #106)

Any ideas/code contributions to move forward on this topic are welcome :pray:

**Comment by camelaissani** [comment]
After some investigations:
1. can be resolved with [this](https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute). 

2. I've found 2 options so far:
- Create a env.js file which will inject the variables in the window object (details [here](https://stackoverflow.com/questions/65521094/nextjs-how-to-get-runtime-environment-variables/74246133#74246133))
- Expose a new endpoint which will compute the variables from the process.env backend side. This new API will be called at the very begining of the UI application startup

**Comment by camelaissani** [comment]
Following the work done on issue #106 almost all environment variables are now passed at runtime on not at build time.

Unfortunately only the `basePath` of the nextjs applications must be passed at build time https://github.com/vercel/next.js/discussions/41769

**Comment by albanshahini** [comment]
@camelaissani this image would make microrealestate so easy to install and use. Instead of taking months, it would take minutes. Please help making this a reality.

**Comment by zeronounours** [comment]
> Following the work done on issue #106 almost all environment variables are now passed at runtime on not at build time.
> 
> Unfortunately only the `basePath` of the nextjs applications must be passed at build time [vercel/next.js#41769](https://github.com/vercel/next.js/discussions/41769)

I'm not sure to understand the issue with `basePath`. The frontend like any other webapp have to be exposed on a specific base path. There is no need to customize this at run time, at the front-end level.

If someone wants to customize the base path to access it, it can rely on the gateway which act as a reverse proxy. You just need to add a `pathRewrite` the frontend entry.

**Comment by zeronounours** [comment]
After some tests, http-proxy-middleware does not seem to be rewriting in-body URL like reverse proxy do. So indeed the issue persist.
Maybe a docker images with non-configurable basepath can created, and when next.js behavior can be bypassed, make it configurable.

**Comment by camelaissani** [comment]
Yes, that’s where my investigations led me.
I've thought about creating Docker images without maintaining a custom base path, but these images will introduce a breaking change for people using the app with a base path.

**Comment by camelaissani** [comment]
@upuldi now no need to build the docker images anymore. The images are available in the Github container registry of the repository.
The installation is a lot simplified see https://github.com/microrealestate/microrealestate#1-install-the-application

@zeronounours I've finally found a hack for the basepath https://github.com/microrealestate/microrealestate/blob/master/webapps/commonui/scripts/replacebasepath.js
