### ISSUE TITLE
Fails to build on Debian 12 with podman

### ISSUE THREAD

**Issue by Swizzler121** [microrealestate/microrealestate#138]
```__  __   _                         ____                   _   _____         _             _          
 |  \/  | (_)   ___   _ __    ___   |  _ \    ___    __ _  | | | ____|  ___  | |_    __ _  | |_    ___ 
 | |\/| | | |  / __| | '__|  / _ \  | |_) |  / _ \  / _` | | | |  _|   / __| | __|  / _` | | __|  / _ \
 | |  | | | | | (__  | |    | (_) | |  _ <  |  __/ | (_| | | | | |___  \__ \ | |_  | (_| | | |_  |  __/
 |_|  |_| |_|  \___| |_|     \___/  |_| \_\  \___|  \__,_| |_| |_____| |___/  \__|  \__,_|  \__|  \___|
                                                                                                       
The application designed to assist landlords in managing their properties and rentals

? Have you created a mailgun account for sending emails 
(https://www.mailgun.com/)? No
? Enter the URL to access the landlord front-end: http://localhost:8080/landlord

? Enter the URL to access the tenant front-end (it should share the same domain 
and port as the landlord front-end URL): http://localhost:8080/tenant
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

Using podman and docker-compose on debian 12

```
$ docker -v
Docker version 20.10.24+dfsg1, build 297e128
$ docker-compose -v
docker-compose version 1.29.2, build unknown
```

**Comment by TechnoSmack** [comment]
Im havign the same issue

**Comment by zeronounours** [comment]
I doubt it will work that easily with podman (through the CLI). However, you can easily run manually with podman and podman-compose (I'm using it). There are few things to change prior to that :

- Prepare the `.env` file:
  - Use `./mre` to initialize the `.env` file by answering questions
  - Copy `base.env` at the to of the `.env` file
- Fix docker-compose files:
  - Reorder sections in all `docker-compose.microservices.base.yml` with the following (podman-compose doesn't manage dependencies well, forcing you to do it for them)
    - minio
    - redis
    - mongo
    - pdfgenerator
    - emailer
    - authenticator
    - api
    - gateway
    - landlord-frontend
    - tenant-frontend
  - Use full name for images of redis and mongo in `docker-compose.microservices.base.yml`: prefix images with `docker.io/`
  - Remove `extra_hosts` from landlord-frontend and tenant-frontend entries. (**it breaks some requests even if still works.**. I don't know why frontend use such hosts instead of direct service call or call through the gateway)

**Comment by camelaissani** [comment]
@zeronounours thanks for your comment. It might be interesting to create a dedicated podman-compose file and adapt the cli to use podman.
I see that you mention `minio`,  I was considering adding it to store localy the documents.

About `extra_hosts` I added it a while ago to let the Next server access the gateway from inside the docker network. We can double check if it is really relevant.
