### ISSUE TITLE
cannot create account on landlord landing page

### ISSUE THREAD

**Issue by TheJollyCoder** [microrealestate/microrealestate#148]
what steps should i take to troubleshoot?
finally got ./mre start to work. i was able to access off my 2nd machine, through "localip":8080/landlord" then when prompted to create a account, i cannot access it.

**Comment by goldenrye** [comment]
I run into the same issue, when i type http://x.x.x.x:8080/tenant in browser I am able to see the page "Sign up to MicroRealEstate". But after I type my name, email and password, it prompts "something went wrong".

**Comment by camelaissani** [comment]
@goldenrye @cmkamba this issue can happen when the front-end cannot connect with the back-end.
Do you see a network issue in the [web browser console](https://developer.chrome.com/docs/devtools/network)?
You may have a wrong url set in  `GATEWAY_URL` in the  .env file.

**Comment by cmkamba** [comment]
my GATEWAY_URL is in the format http://10.X.Y.Z:8080 

Also i am getting gateway timed out on the console/network

**Comment by camelaissani** [comment]
I suspect that you have not achieved to build all the services because of not enough ram/cpus.

I tried to reproduce on my side by installing the app on a VPS with 2 vCore, 2Go Ram and 80 Go SSD.
The build has not completed in one shot the frontend services eat a lot of resources (RAM and CPUs). 
A possible workaround is to build one service at a time.

Running the following commands works for me:

1. `./mre build --service gateway`

My answers to the prompts:
```
? Do you want the database to be populated with? no data (keep existing data)
? Select your email delivery service? (required for password reset and tenant sign in) None
? Enter the URL to access the landlord front-end: http://W.X.Y.Z:8080/landlord
? Enter the URL to access the tenant front-end: http://W.X.Y.Z:8080/tenant
```

2. `./mre build --service authenticator`
3. `./mre build --service api`
4. `./mre build --service tenantapi`
5. `./mre build --service emailer`
6. `./mre build --service pdfgenerator`
7. `./mre build --service tenant-frontend`
8. `./mre build --service landlord-frontend`  (this service is the most greedy)

These commands produced 8 docker images. The `docker images` command returned:

```
mre/landlord-frontend 
mre/tenant-frontend
mre/gateway
mre/api   
mre/authenticator
mre/tenantapi 
mre/emailer 
mre/pdfgenerator
```

After starting the app `./mre start` I was able to connect on http://W.X.Y.Z:8080/landlord and create an account.

**Comment by goldenrye** [comment]
Thank you @camelaissani 

I change another vm with large memory and storage but after I check out the source code and try to build with ./mre build, build fails with the following information:
The Compose file './docker-compose.microservices.base.yml' is invalid because:
services.api.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.authenticator.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.emailer.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.landlord-frontend.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.mongo.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.pdfgenerator.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.redis.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.tenant-frontend.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.tenantapi.expose is invalid: should be of the format 'PORT[/PROTOCOL]'

I checked the .env file that seems generated by ./mre, there is no API_PORT=8200 definition as base.env, should I copy the base.env to .env manually before I run ./mre build? Or is there some depended package broken? I am using Ubuntu22.04 with docker and docker-swamp installed via 'apt install docker.io' and 'apt install docker-compose'

**Comment by bhaktatejas922** [comment]
^ getting same error

**Comment by camelaissani** [comment]
@TheJollyCoder @bhaktatejas922 @goldenrye @cmkamba Please follow the new installation procedure https://github.com/microrealestate/microrealestate#1-install-the-application 
This should fix the issue.

**Comment by goldenrye** [comment]
@camelaissani I follow the instruction but the same error "something went wrong" still happens during tenant signup

**Comment by camelaissani** [comment]
@goldenrye I think your problem is the way you installed docker. Please reinstall it by following this documentation https://docs.docker.com/engine/install/ubuntu/

**Comment by goldenrye** [comment]
@camelaissani I remove and re-install the docker via apt repository by following https://docs.docker.com/engine/install/ubuntu/ but doesn't help. 

using chrome developer tool, I see there are internal errors during signup, here is the screen-shot,
<img width="550" alt="sign_up" src="https://github.com/microrealestate/microrealestate/assets/16398268/46b25541-45ad-41c8-81e5-1541b5724b66">

**Comment by JxIMx** [comment]
Hello, I'am having the same issue, willing to provide any logs needed.
also I tried to install in Linux, Debian and windows server and got the same result in all those.

**Comment by camelaissani** [comment]
@JxIMx hello can you describe with more details what's happening on your side? Docker logs might help to spot the problem. Thanks

**Comment by JxIMx** [comment]
Hello @camelaissani  Thanks for taking the time to answer me. Sorry I'm new in all of this docker stuff but let me show you the steps and commands I'm using and the error I'm getting.
![imagen](https://github.com/microrealestate/microrealestate/assets/138330431/4f406325-f1c7-47bd-bdb8-0017aa6bcc36)

This is a Debian 12 server that I created to only run container and I install on it Portainer.

But when I go to the web GUI I got this error
![imagen](https://github.com/microrealestate/microrealestate/assets/138330431/a648d32e-7740-46ea-a09d-63df3b9886b7)


Its there a specific docker log that I need to check?? When I go to Portainer GUI all the containers looks fine.
![imagen](https://github.com/microrealestate/microrealestate/assets/138330431/b786a8a5-563b-47c0-8a68-e0c0b8357c4b)

**Comment by camelaissani** [comment]
@JxIMx Thanks for the details.
Can you try to reconfigure the application and use the same url than the one you used to access the app on your browser? 
![Screenshot from 2024-03-31 20-02-31](https://github.com/microrealestate/microrealestate/assets/7079471/687e564a-5201-48e2-9d8b-114d2a09d642)
The url above should not be localhost but the one used in your browser (portainer...)

**Comment by camelaissani** [comment]
Soon you will have a version that will work perfectly on mobile 😉

**Comment by JxIMx** [comment]
Sorry I didnt reply earlier, @camelaissani I would like to help this project translating it to Spanish since I'am Spanish native speaker (Panamá). 
Is it posible? how could I do it?? and again thanks a lot for fixing the issue I was having.

**Comment by DHH00** [comment]
I would try microrealestate ! But i can create an account or log in. Could anybody help me, please ?

<img width="928" alt="5" src="https://github.com/user-attachments/assets/d2aca501-f1b5-4c61-901b-5babae713b71">
The application didn't start, but it's running
<img width="920" alt="3" src="https://github.com/user-attachments/assets/2bc0de1b-e417-4a6f-ae42-1082e1658c64">
<img width="929" alt="4" src="https://github.com/user-attachments/assets/3e6fe7c9-dcb6-43cc-8305-9b2471ee9adf">

COnfig files
 
[_microrealestate_pdfgenerator_1_logs.txt](https://github.com/user-attachments/files/17976264/_microrealestate_pdfgenerator_1_logs.txt)
[_microrealestate_redis_1_logs.txt](https://github.com/user-attachments/files/17976265/_microrealestate_redis_1_logs.txt)
[_microrealestate_tenantapi_1_logs.txt](https://github.com/user-attachments/files/17976266/_microrealestate_tenantapi_1_logs.txt)
[_microrealestate_tenant-frontend_1_logs.txt](https://github.com/user-attachments/files/17976267/_microrealestate_tenant-frontend_1_logs.txt)
[_microrealestate_gateway_1_logs.txt](https://github.com/user-attachments/files/17976269/_microrealestate_gateway_1_logs.txt)

[_microrealestate_landlord-frontend_1_logs.txt](https://github.com/user-attachments/files/17976261/_microrealestate_landlord-frontend_1_logs.txt)
[_microrealestate_mongo_1_logs.txt](https://github.com/user-attachments/files/17976263/_microrealestate_mongo_1_logs.txt)

Thanks
