### ISSUE TITLE
yml unsupported

### ISSUE THREAD

**Issue by drique** [microrealestate/microrealestate#3]
Can't run mre start with the current yml file versions.
Works if I use v 2.
On ubuntu 16.04
Docker version 18.06.0-ce

```
ERROR: Version in "././docker-compose.monitoring.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by camelaissani** [comment]
Given the [compatibility matrix](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix) it should work.
I don't understand what's wrong there.

Could you give me the docker-compose version installed on your side?
```bash
docker-compose --version
```

**Comment by drique** [comment]
docker-compose version 1.8.0, build unknown

**Comment by camelaissani** [comment]
@drique Have you retried to run the command recently?

**Comment by mr-techiee** [comment]
can't run the project, I configured my project as I said mentioned above, but when I try to run the project as locally I can't run it, can u plz help me out this issue?

**Comment by camelaissani** [comment]
@mr-techiee Could you give me more details of what is not working? Do you have some logs?

**Comment by abocoum** [comment]
hi, 
when i try to build the first time. this is my log

### Log 
': not a valid identifier
': not a valid identifier
': not a valid identifier
Building microrealestate...
ERROR: The Compose file '././docker-compose.monitoring.yml' is invalid because:
services.logstash.ports contains an invalid type, it should be a number, or an object
services.logstash.ports contains an invalid type, it should be a number, or an object
services.kibana.ports contains an invalid type, it should be a number, or an object
services.cadvisor.ports contains an invalid type, it should be a number, or an object
services.elasticsearch.ports contains an invalid type, it should be a number, or an object



Can you help me please?

**Comment by camelaissani** [comment]
@abocoum did you use the `./mre build` command to build the docker images?
The problem here is like the environment variables set in the docker-compose file are not correctly subtituted.
Actualy, the `mre` command read the environment variable values from either `prod.env` or `dev.env` files to inject them to the compose files (https://github.com/microrealestate/microrealestate/blob/master/mre#L10)
